export const GET_COCKTAILS_REQ = 'GET_COCKTAILS_REQUEST';
export const GET_USER_REQ = 'GET_USER_REQ';
export const GET_FAVOURITES_REQ = 'GET_FAVOURITE_REQ';
export const FAVOURITE_COCKTAILS_REQ = 'FAVOURITE_COCKTAILS_REQ';
// TODO const GET_SINGLE_COCKTAIL_REQ = 'GET_SINGLE_COCKTAIL_REQ'
