const GET_COCKTAILS_REQ = 'GET_COCKTAILS_REQUEST';
const GET_USER_REQ = 'GET_USER_REQ';
// export const GET_FAVOURITES_REQ = 'GET_FAVOURITE_REQ';
const GET_FAVOURITE_COCKTAILS_REQ = 'GET_FAVOURITE_COCKTAILS_REQ';
// export const CREATE_NEW_FAVOURITE = 'CREATE_NEW_FAVOURITE';
// TODO const GET_SINGLE_COCKTAIL_REQ = 'GET_SINGLE_COCKTAIL_REQ'

export {
  GET_COCKTAILS_REQ, GET_USER_REQ, GET_FAVOURITE_COCKTAILS_REQ,
};
